name: msys2-modern

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  msys2:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sys:
          - mingw64
          - ucrt64
    name: ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - run: git config --global core.autocrlf input
        shell: bash
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            git
            base-devel
            tree
            zip
          pacboy: >-
            toolchain:p
            gtk3:p
            adwaita-icon-theme:p
            libgcrypt:p
            meson:p
            imagemagick:p

      - name: Run makepkg-mingw (Build & Test & Install)
        run: |
          git archive --prefix gtkhash/ -o msys2/mingw-w64-gtkhash/gtkhash.tar.gz HEAD
          cd msys2/mingw-w64-gtkhash
          PKGEXT=.pkg.tar.xz makepkg-mingw --noconfirm --noprogressbar --syncdeps --clean --cleanbuild --force
          pacman -U --noconfirm *.pkg.tar.xz

      - name: Run Modern Bundle Script
        run: |
          chmod +x msys2/bundle.sh
          ./msys2/bundle.sh

      - name: Create ZIP Archive
        run: |
          cd msys2/dist
          zip -r ../../gtkhash-${{ matrix.sys }}-portable.zip ./*

      - name: Build Inno Setup Installer (.exe)
        shell: cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" msys2\gtkhash.iss

      - name: Move Installer for Upload
        shell: bash
        run: |
          mv msys2/gtkhash-installer.exe ./gtkhash-${{ matrix.sys }}-installer.exe

      - uses: actions/upload-artifact@v4
        with:
          name: gtkhash-${{ matrix.sys }}-packages
          if-no-files-found: error
          path: |
            gtkhash-${{ matrix.sys }}-portable.zip
            gtkhash-${{ matrix.sys }}-installer.exe